### ISSUE TITLE
Driver support roadmap

### ISSUE THREAD

**Issue by andrewgryan** [MetOffice/forest#234]
- [x] Add standard lib format templating to config.yml
    --param 'x:value'
- [x] Remove `--directory`
- [x] Remove `--database` #235 
- [ ] Use `label` (not `pattern`) as primary navigation key
- [ ] Create list of DatasetSpecs to configure existing code
- [ ] Migrate first dataset, mixed list DatasetSpec|Dataset
- [ ] Migrate all the other datasets
- [ ] `--show-config` prints post-substitution config only and ends program, user can
   pipe it wherever they want
